
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.container_name }}
  labels:
    app: {{ .Values.container_name }}
    env: {{ .Values.global.env }}
    region: {{ .Values.global.aws.region }}
data:
{{- range $key, $value := .Values.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}